FROM python:3.11-slim

WORKDIR /app

COPY requirements-consumer.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer.py .

ENTRYPOINT ["python", "-u", "consumer.py"]
